# Managed by The Whimsical Lands Owner Studio.
launcher.version=1.1.1
launcher.jar.url=releases/the-whimsical-lands-player-launcher-1.1.1.jar
launcher.jar.sha256=19248c8d5c719977f479402cd7d3c39df5793afbf2bab0c5aa88147b3d2da4cb
bootstrapper.jar.url=releases/launcher-bootstrapper-1.1.1.jar
bootstrapper.jar.sha256=c1bb405666f95663177dff808dc892a28b7420ea28db11152b92090473022c01
launcher.mandatory=false
launcher.notes=Redesigned launcher and Admin Studio.
