# Managed by The Whimsical Lands Owner Studio.
launcher.version=1.12.0
launcher.jar.url=releases/the-whimsical-lands-player-launcher-1.12.0.jar
launcher.jar.sha256=4b799d9f5ee1357b2f6744fb7415a266d3147d7534f8ce9e66689e161069a4a1
bootstrapper.jar.url=releases/launcher-bootstrapper-1.12.0.jar
bootstrapper.jar.sha256=9f6377ef93c0e7743a7f69f5edaa56af97ab2d1e775d7ca8eabbb0edc80bc118
launcher.mandatory=false
launcher.notes=Adds the project Command Center, blueprint file roles, improved threads, studio-level team directory, and visual card composer.
