#  Main header!
#  Line 2

[songs]
	[songs.21stHallTrack]
		triggers = [ "zones-Moria", "dimension-moria" ]
	[songs.ABigWorldForASmallHobbitTrack]
		triggers = [ "zones-BrandybuckHall", "dimension-arda" ]
	[songs.ArdaCraftThemeTrack]
		triggers = [ "menu" ]
	[songs.BarrowDownsTrack]
		triggers = [ "zones-BarrowDowns", "dimension-arda" ]
	[songs.BombadilTrack]
		triggers = [ "zones-Bombadil", "dimension-arda" ]
	[songs.BonusTrack]
		triggers = [ "dimension-arda", "zones-PrancingPony" ]
	[songs.BreeTrack]
		triggers = [ "zones-Bree", "dimension-arda" ]
	[[songs.CarasGaladhonTrack]]
		triggers = [ "zones-CarasGaladhon", "dimension-arda" ]
		chance = 100
		play_once = 1
	[[songs.CarasGaladhonTrack]]
		triggers = [ "zones-Mithlond", "dimension-arda" ]
		chance = 1
		play_once = 1
	[[songs.CarasGaladhonTrack]]
		triggers = [ "zones-CerinAmroth", "dimension-arda" ]
		chance = 1
		play_once = 1
	[songs.CloudsAndRainTrack]
		triggers = [ "zones-GwarEstel", "dimension-arda" ]
	[[songs.GondorTrack]]
		triggers = [ "zones-Lisclorn", "dimension-arda" ]
	[[songs.GondorTrack]]
		triggers = [ "zones-TalRimmon", "dimension-arda" ]
	[songs.HelmsDeepTrack]
		triggers = [ "zones-HelmsDeep", "dimension-arda" ]
	[[songs.KhazadDumTrack]]
		triggers = [ "zones-OldMoria", "zones-Moria" ]
	[[songs.LaurelinsFruitTrack]]
		triggers = [ "zones-CerinAmroth", "dimension-arda" ]
		chance = 100
		play_once = 1
	[[songs.LaurelinsFruitTrack]]
		triggers = [ "zones-CarasGaladhon", "dimension-arda" ]
		chance = 1
		play_once = 1
	[[songs.LaurelinsFruitTrack]]
		triggers = [ "zones-Mithlond", "dimension-arda" ]
		chance = 1
		play_once = 1
	[songs.LindonTrack]
		triggers = [ "zones-Mithlond", "dimension-arda" ]
		chance = 100
		play_once = 1
	[songs.MinasTirithTrack]
		triggers = [ "zones-MinasTirith", "dimension-arda" ]
	[songs.MordorTrack]
		triggers = [ "zones-IsengardTunnels", "dimension-arda" ]
	[songs.MoriaTrack]
		triggers = [ "dimension-moriadimension", "zones-Moria" ]
	[[songs.RivendellTrack]]
		triggers = [ "zones-Rivendell", "dimension-arda" ]
		chance = 100
	[[songs.RivendellTrack]]
		triggers = [ "zones-Mithlond", "dimension-arda" ]
		chance = 1
		play_once = 1
	[songs.RohanTrack]
		triggers = [ "zones-Edoras", "dimension-arda" ]
	[[songs.RuinsofArnorTrack]]
		triggers = [ "zones-Tharbad", "dimension-arda" ]
	[[songs.RuinsofArnorTrack]]
		triggers = [ "zones-Weathertop", "dimension-arda" ]
	[[songs.RuinsofArnorTrack]]
		triggers = [ "zones-Annuminas", "dimension-arda" ]
	[[songs.RuinsofArnorTrack]]
		triggers = [ "zones-Fornost", "dimension-arda" ]
	[songs.SoundInTheHallsTrack]
		triggers = [ "zones-ThorinsHalls", "dimension-arda" ]
	[[songs.TelperionsFlowerTrack]]
		triggers = [ "zones-CarasGaladhon", "dimension-arda" ]
		chance = 1
	[[songs.TelperionsFlowerTrack]]
		triggers = [ "zones-Mithlond", "dimension-arda" ]
		chance = 1
	[songs.TheGreatRiverTrack]
		triggers = [ "zones-Argonath", "dimension-arda" ]
	[songs.TheInfiniteTrack]
		triggers = [ "zones-OstInEdhil", "dimension-arda" ]
	[songs.TheOldForestTrack]
		triggers = [ "zones-OldForest", "dimension-arda" ]
	[[songs.TheShireTrack]]
		triggers = [ "zones-Hobbiton", "dimension-arda" ]
	[songs.TheSicknessOfMorgothTrack]
		triggers = [ "zones-Orthanc", "dimension-arda" ]
	[[songs.TheSongOfTheAinurTrack]]
		triggers = [ "zones-CerinAmroth", "dimension-arda" ]
		chance = 1
		play_once = 1
	[[songs.TheSongOfTheAinurTrack]]
		triggers = [ "zones-CarasGaladhon", "dimension-arda" ]
		chance = 1
		play_once = 1
	[[songs.TheSongOfTheAinurTrack]]
		triggers = [ "zones-Mithlond", "dimension-arda" ]
		chance = 1
		play_once = 1
	[[songs.WestGateTrack]]
		triggers = [ "zones-WestGate", "dimension-arda" ]

[triggers]
	[[triggers.dimension]]
		identifier = "arda"
		resource_name = [ "overworld" ]
		ticks_between_audio = "1200"
	[[triggers.dimension]]
		fade_in = "50"
		identifier = "moriadimension"
		resource_name = [ "moria" ]
		ticks_between_audio = "1200"
	[[triggers.dimension]]
		identifier = "freebuild"
		resource_name = [ "freebuild" ]
		ticks_between_audio = "1200"
	[triggers.menu]
		fade_out = "50"
	[triggers.universal]
		active_cooldown = "0"
		fade_in = "0"
		fade_out = "0"
		persistence = "0"
		ticks_before_active = "0"
		ticks_before_audio = "0"
		ticks_between_audio = "0"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "HelmsDeep"
		zone_max_x = "8750"
		zone_max_y = "2147"
		zone_max_z = "12065"
		zone_min_x = "8300"
		zone_min_y = "-2147"
		zone_min_z = "11700"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "OstInEdhil"
		zone_max_x = "7800"
		zone_max_y = "2147"
		zone_max_z = "4500"
		zone_min_x = "7360"
		zone_min_y = "-2147"
		zone_min_z = "4240"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Orthanc"
		zone_max_x = "7820"
		zone_max_y = "2147"
		zone_max_z = "9667"
		zone_min_x = "7740"
		zone_min_y = "-2147"
		zone_min_z = "9605"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "OldMoria"
		zone_max_x = "2665"
		zone_max_z = "1950"
		zone_min_x = "2300"
		zone_min_z = "1150"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "MinasTirith"
		zone_max_x = "17840"
		zone_max_y = "2147"
		zone_max_z = "16400"
		zone_min_x = "17000"
		zone_min_y = "-2147"
		zone_min_z = "15740"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "BarrowDowns"
		zone_max_x = "1700"
		zone_max_y = "2147"
		zone_max_z = "540"
		zone_min_x = "860"
		zone_min_y = "-2147"
		zone_min_z = "-720"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "ThorinsHalls"
		zone_max_x = "-6710"
		zone_max_y = "2147"
		zone_max_z = "-2350"
		zone_min_x = "-7640"
		zone_min_y = "-2147"
		zone_min_z = "-2860"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "BrandybuckHall"
		zone_max_x = "90"
		zone_max_y = "2147"
		zone_max_z = "-145"
		zone_min_x = "-224"
		zone_min_y = "-2147"
		zone_min_z = "-460"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Fornost"
		zone_max_x = "1864"
		zone_max_y = "2147"
		zone_max_z = "-2526"
		zone_min_x = "1044"
		zone_min_y = "-2147"
		zone_min_z = "-3092"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Mithlond"
		zone_max_x = "-5340"
		zone_max_y = "2147"
		zone_max_z = "66"
		zone_min_x = "-6256"
		zone_min_y = "-2149"
		zone_min_z = "-930"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Annuminas"
		zone_max_x = "-954"
		zone_max_y = "2147"
		zone_max_z = "-2350"
		zone_min_x = "-1900"
		zone_min_y = "-2147"
		zone_min_z = "-2810"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "TalRimmon"
		zone_max_x = "15583"
		zone_max_y = "2147"
		zone_max_z = "14918"
		zone_min_x = "15250"
		zone_min_y = "-2147"
		zone_min_z = "14732"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "CerinAmroth"
		zone_max_x = "12255"
		zone_max_y = "2147"
		zone_max_z = "4740"
		zone_min_x = "12030"
		zone_min_y = "-2147"
		zone_min_z = "4540"
	[[triggers.zones]]
		fade_in = "200"
		fade_out = "100"
		identifier = "IsengardTunnels"
		zone_max_x = "8040"
		zone_max_y = "26"
		zone_max_z = "9860"
		zone_min_x = "7550"
		zone_min_z = "9400"
	[[triggers.zones]]
		fade_in = "50"
		fade_out = "30"
		identifier = "Moria"
		ticks_between_audio = "1200"
		zone_max_x = "2650"
		zone_max_y = "2147"
		zone_max_z = "3070"
		zone_min_x = "0"
		zone_min_y = "-2147"
		zone_min_z = "0"
	[[triggers.zones]]
		fade_out = "200"
		identifier = "Caradhras"
		zone_max_x = "10510"
		zone_max_y = "2147"
		zone_max_z = "5090"
		zone_min_x = "8912"
		zone_min_y = "-2147"
		zone_min_z = "2590"
	[[triggers.zones]]
		fade_in = "20"
		fade_out = "20"
		identifier = "PrancingPony"
		priority = "100"
		zone_max_x = "2306"
		zone_max_y = "2147"
		zone_max_z = "-249"
		zone_min_x = "2281"
		zone_min_y = "-2147"
		zone_min_z = "-275"
	[[triggers.zones]]
		fade_out = "200"
		identifier = "OldForest"
		zone_max_x = "728"
		zone_max_y = "2147"
		zone_max_z = "520"
		zone_min_x = "132"
		zone_min_y = "-2147"
		zone_min_z = "-630"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Weathertop"
		zone_max_x = "4770"
		zone_max_y = "2147"
		zone_max_z = "-215"
		zone_min_x = "4055"
		zone_min_y = "-2147"
		zone_min_z = "-600"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "GwarEstel"
		zone_max_x = "8200"
		zone_max_y = "2147"
		zone_max_z = "150"
		zone_min_x = "8015"
		zone_min_y = "-2147"
		zone_min_z = "-40"
	[[triggers.zones]]
		fade_out = "200"
		identifier = "CarasGaladhon"
		zone_max_x = "12574"
		zone_max_y = "2147"
		zone_max_z = "5325"
		zone_min_x = "12105"
		zone_min_y = "-2147"
		zone_min_z = "4835"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Edoras"
		zone_max_x = "10900"
		zone_max_y = "2700"
		zone_max_z = "13232"
		zone_min_x = "10140"
		zone_min_y = "-2000"
		zone_min_z = "12700"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Bree"
		priority = "10"
		zone_max_x = "3020"
		zone_max_y = "2147"
		zone_max_z = "450"
		zone_min_x = "1826"
		zone_min_y = "-2147"
		zone_min_z = "-800"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Argonath"
		zone_max_x = "15812"
		zone_max_y = "2147"
		zone_max_z = "12646"
		zone_min_x = "15258"
		zone_min_y = "-2147"
		zone_min_z = "11353"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Lisclorn"
		zone_max_x = "17550"
		zone_max_y = "2147"
		zone_max_z = "14537"
		zone_min_x = "17259"
		zone_min_y = "-2147"
		zone_min_z = "14380"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Tharbad"
		zone_max_x = "4270"
		zone_max_y = "2100"
		zone_max_z = "4850"
		zone_min_x = "3190"
		zone_min_y = "-2147"
		zone_min_z = "3666"
	[[triggers.zones]]
		fade_out = "300"
		identifier = "Hobbiton"
		zone_max_x = "-1280"
		zone_max_y = "2147"
		zone_max_z = "-610"
		zone_min_x = "-1570"
		zone_min_y = "-2147"
		zone_min_z = "-970"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Rivendell"
		priority = "5"
		zone_max_x = "10400"
		zone_max_y = "2147"
		zone_max_z = "-400"
		zone_min_x = "9700"
		zone_min_y = "-2100"
		zone_min_z = "-840"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "Bombadil"
		zone_max_x = "829"
		zone_max_y = "2147"
		zone_max_z = "-358"
		zone_min_x = "785"
		zone_min_y = "-2147"
		zone_min_z = "-414"
	[[triggers.zones]]
		fade_out = "30"
		identifier = "WestGate
		zone_max_x = "9240"
		zone_max_y = "100"
		zone_max_z = "4150"
		zone_min_x = "8880"
		zone_min_y = "-2147"
		zone_min_z = "3900"